import React, { FC, useEffect } from 'react';
import { useLocale } from '../contexts/LocaleContext';
import { XIcon, CubeIcon } from './Icons';
import '../types';

interface ArVrModalProps {
    isOpen: boolean;
    onClose: () => void;
    modelUrl: string | null;
}

export const ArVrModal: FC<ArVrModalProps> = ({ isOpen, onClose, modelUrl }) => {
    const { t } = useLocale();

    useEffect(() => {
        const handleKeyDown = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                onClose();
            }
        };

        if (isOpen) {
            document.addEventListener('keydown', handleKeyDown);
        }

        return () => {
            document.removeEventListener('keydown', handleKeyDown);
        };
    }, [isOpen, onClose]);

    if (!isOpen) {
        return null;
    }

    return (
        <div 
            className="fixed inset-0 bg-black/70 backdrop-blur-lg z-50 flex items-center justify-center p-4 animate-fade-in" 
            style={{animationDuration: '0.2s'}}
            onClick={onClose}
            role="dialog"
            aria-modal="true"
            aria-labelledby="ar-vr-modal-title"
        >
            <div 
                className="bg-base-100 dark:bg-dark-base-300 rounded-2xl shadow-2xl w-full max-w-4xl h-[85vh] flex flex-col border border-base-300 dark:border-dark-base-200"
                onClick={(e) => e.stopPropagation()}
            >
                <header className="p-4 border-b border-base-200 dark:border-dark-base-200 flex items-center justify-between flex-shrink-0">
                    <h2 id="ar-vr-modal-title" className="text-lg font-bold text-text-primary dark:text-dark-text-primary flex items-center gap-2">
                        <CubeIcon className="w-6 h-6 text-brand-primary" />
                        {t('arVrModalTitle')}
                    </h2>
                    <button onClick={onClose} className="p-2 -mr-2 rounded-full text-text-secondary dark:text-dark-text-secondary hover:bg-base-200 dark:hover:bg-dark-base-200 transition-colors" aria-label={t('close')}>
                        <XIcon className="w-6 h-6" />
                    </button>
                </header>
                <main className="flex-grow relative bg-base-200/50 dark:bg-dark-base-200/20">
                    {modelUrl ? (
                        <model-viewer
                            src={modelUrl}
                            alt="A 3D model generated by Universum"
                            camera-controls
                            auto-rotate
                            ar
                            shadow-intensity="1"
                            style={{ width: '100%', height: '100%' }}
                        ></model-viewer>
                    ) : (
                        <div className="w-full h-full flex items-center justify-center text-center text-text-secondary dark:text-dark-text-secondary p-4">
                           <p>{t('noModelGeneratedMessage')}</p>
                        </div>
                    )}
                </main>
                 <footer className="p-3 text-center text-xs text-text-secondary dark:text-dark-text-secondary border-t border-base-200 dark:border-dark-base-200 flex-shrink-0">
                    {t('arVrModalDescription')}
                </footer>
            </div>
        </div>
    );
};