import React, { FC } from 'react';
import '../types';

interface ArVrModelViewerProps {
    modelUrl: string;
}

export const ArVrModelViewer: FC<ArVrModelViewerProps> = ({ modelUrl }) => {
    return (
        <div className="w-full aspect-square max-w-sm rounded-lg overflow-hidden border border-base-300 dark:border-dark-base-200 bg-base-200/50 dark:bg-dark-base-200/20 relative">
            <model-viewer
                src={modelUrl}
                alt="A 3D model generated by Universum"
                camera-controls
                auto-rotate
                ar
                shadow-intensity="1"
                style={{ width: '100%', height: '100%' }}
            ></model-viewer>
        </div>
    );
};